global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'chatwolf'
    environment: 'production'

scrape_configs:
  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']
        labels:
          application: 'alloy'
          service: 'alloy'
  
  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka:8761']
        labels:
          application: 'eureka'
          service: 'eureka'

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:7000']
        labels:
          application: 'gateway'
          service: 'gateway'

  - job_name: 'auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth:7100']
        labels:
          application: 'auth'
          service: 'auth'

  - job_name: 'socket'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['socket:7200']
        labels:
          application: 'socket'
          service: 'socket'

  - job_name: 'consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['consumer:7300']
        labels:
          application: 'consumer'
          service: 'consumer'
    
  - job_name: 'presence'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['presence:7400']
        labels:
          application: 'presence'
          service: 'presence'
